# Generated by Django 5.2.4 on 2025-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon raqami')),
                ('code', models.CharField(max_length=5, verbose_name='Tasdiqlash kodi')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilganmi')),
            ],
            options={
                'verbose_name': 'Login Kod',
                'verbose_name_plural': 'Login Kodlar',
                'indexes': [models.Index(fields=['phone', 'expires_at'], name='accounts_lo_phone_307347_idx'), models.Index(fields=['telegram_id'], name='accounts_lo_telegra_1130f3_idx'), models.Index(fields=['code', 'expires_at'], name='accounts_lo_code_e36358_idx')],
            },
        ),
    ]
